import Foundation

/// Feature flags from global `feature_access`.
public enum FeatureAccess: String, Codable, Hashable, Sendable {
    case accessForbidAll = "ACCESS_FORBID_ALL"
    case forbidAll = "FEATURE_ACCESS_FORBID_ALL"
    case addCameraToLayoutInMonitoring = "FEATURE_ACCESS_ADD_CAMERA_TO_LAYOUT_IN_MONITORING"
    case allowButtonMenuCamera = "FEATURE_ACCESS_ALLOW_BUTTON_MENU_CAMERA"
    case allowDeleteRecords = "FEATURE_ACCESS_ALLOW_DELETE_RECORDS"
    case allowShowFacesInLive = "FEATURE_ACCESS_ALLOW_SHOW_FACES_IN_LIVE"
    case allowShowPrivacyVideoInArchive = "FEATURE_ACCESS_ALLOW_SHOW_PRIVACY_VIDEO_IN_ARCHIVE"
    case allowShowTitles = "FEATURE_ACCESS_ALLOW_SHOW_TITLES"
    case allowUnprotectedExport = "FEATURE_ACCESS_ALLOW_UNPROTECTED_EXPORT"
    case archivesSetup = "FEATURE_ACCESS_ARCHIVES_SETUP"
    case changingLayouts = "FEATURE_ACCESS_CHANGING_LAYOUTS"
    case confidentialBookmarks = "FEATURE_ACCESS_CONFIDENTIAL_BOOKMARKS"
    case detectorsSetup = "FEATURE_ACCESS_DETECTORS_SETUP"
    case devicesSetup = "FEATURE_ACCESS_DEVICES_SETUP"
    case domainManagingOps = "FEATURE_ACCESS_DOMAIN_MANAGING_OPS"
    case editPtzPresets = "FEATURE_ACCESS_EDIT_PTZ_PRESETS"
    case export = "FEATURE_ACCESS_EXPORT"
    case groupPanel = "FEATURE_ACCESS_GROUP_PANEL"
    case isGuardRole = "FEATURE_ACCESS_IS_GUARD_ROLE"
    case layoutsTab = "FEATURE_ACCESS_LAYOUTS_TAB"
    case minMaxButtonAllowed = "FEATURE_ACCESS_MINMAX_BUTTON_ALLOWED"
    case objectPanelAndCameraSearchPanel = "FEATURE_ACCESS_OBJECT_PANEL_AND_CAMERA_SEARCH_PANEL"
    case programmingSetup = "FEATURE_ACCESS_PROGRAMMING_SETUP"
    case realtimeRecognitionSetup = "FEATURE_ACCESS_REALTIME_RECOGNITION_SETUP"
    case search = "FEATURE_ACCESS_SEARCH"
    case settingsSetup = "FEATURE_ACCESS_SETTINGS_SETUP"
    case showErrorMessages = "FEATURE_ACCESS_SHOW_ERROR_MESSAGES"
    case systemJournal = "FEATURE_ACCESS_SYSTEM_JOURNAL"
    case usersRightsSetup = "FEATURE_ACCESS_USERS_RIGHTS_SETUP"
    case webUILogin = "FEATURE_ACCESS_WEB_UI_LOGIN"
}
